name: Verify Secret in Prod

on:
  push:
    branches:
      - release

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Output Secret
        run: echo ${{ secrets.MY_SECRET }}
